In [ ]:
"""
Parte 1.

    Selecciona o crea un archivo CSV (puede ser de clientes, ventas, productos, etc.).
        Puedes generarlo manualmente o descargar uno sencillo.
    Utilizando Pandas, realiza lo siguiente:

    Cargar el archivo:"""

import pandas as pd
from IPython.display import display

df = pd.read_csv("Chocolate_Sales.csv")
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
df = pd.read_csv(url)

#Mostrar las primeras filas:
display(df.head())

"""Identificar: número de filas y columnas"""
"""tipos de datos"""
"""valores nulos"""
display(df.info())

,Order_ID,Product,Country,Channel,Salesperson,Order_Date,Discount_Pct,Price_per_Box,Marketing_Spend,Boxes_Shipped,Amount
0,ORD-069833,Truffle Gift Box,Australia,Retail,Arjun Mehta,2022-12-11,3.5,13.72,202.03,71,912.31
1,ORD-090726,85% Dark Bar,Australia,Retail,Arjun Mehta,2023-03-14,9.4,3.30,55.18,84,245.91
2,ORD-042159,70% Dark Bar,Japan,Retail,Hannah Müller,2023-12-21,4.9,18.21,60.65,35,583.7
3,ORD-197166,Hazelnut Milk Bar,Germany,Retail,Arjun Mehta,2023-12-18,15.0,2.66,52.00,92,211.27
4,ORD-112162,Almond Crunch Bar,Australia,Retail,Yuki Sato,2023-08-18,4.4,2.75,187.44,214,549.69

<class 'pandas.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 11 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   Order_ID         200000 non-null  str
 1   Product          200000 non-null  str
 2   Country          200000 non-null  str
 3   Channel          200000 non-null  str
 4   Salesperson      200000 non-null  str
 5   Order_Date       199563 non-null  str
 6   Discount_Pct     199511 non-null  float64
 7   Price_per_Box    199543 non-null  float64
 8   Marketing_Spend  199539 non-null  float64
 9   Boxes_Shipped    200000 non-null  int64
 10  Amount           200000 non-null  str
dtypes: float64(3), int64(1), str(7)
memory usage: 16.8 MB

None

In [8]:
"""Parte 2.

    Realiza al menos dos de las siguientes acciones:

    Eliminar valores nulos
    Rellenar datos faltantes
    Filtrar registros (por ejemplo: mayores a cierta edad)
    Crear una nueva columna (por ejemplo: clasificación)
    Convertir tipos de datos"""
#Rellenar datos faltantes de Order_date
df['Order_Date'] = df['Order_Date'].fillna(df['Order_Date'].mode()[0])
#Crear nueva columna
df['Price_Pre_Discount'] = (df['Price_per_Box'] * 100)/ (100 - df['Discount_Pct'])
#Eliminando cajas no entregadas
df = df[df['Boxes_Shipped'] > 0]

display(df.info())

<class 'pandas.DataFrame'>
Index: 198044 entries, 0 to 199999
Data columns (total 12 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   Order_ID            198044 non-null  str
 1   Product             198044 non-null  str
 2   Country             198044 non-null  str
 3   Channel             198044 non-null  str
 4   Salesperson         198044 non-null  str
 5   Order_Date          198044 non-null  str
 6   Discount_Pct        197560 non-null  float64
 7   Price_per_Box       197590 non-null  float64
 8   Marketing_Spend     197589 non-null  float64
 9   Boxes_Shipped       198044 non-null  int64
 10  Amount              198044 non-null  str
 11  Price_Pre_Discount  197153 non-null  float64
dtypes: float64(4), int64(1), str(7)
memory usage: 19.6 MB

None

In [9]:
"""Parte 3.

    Utiliza Pandas para:

    Obtener estadísticas básicas: df.describe()

    Realizar al menos un análisis, por ejemplo:
        promedio
        conteo por categoría
        agrupación (groupby)"""

display(df.describe())
#Promedio de marketing gastado por País
display(df.groupby('Country')[['Marketing_Spend', 'Boxes_Shipped']].mean())
display(df.groupby('Country').count())

,Discount_Pct,Price_per_Box,Marketing_Spend,Boxes_Shipped,Price_Pre_Discount
count,197560.000000,197590.000000,197589.000000,198044.000000,197153.000000
mean,13.109083,5.908669,95.444763,142.337077,6.825104
std,6.374145,4.952915,66.211603,115.352422,5.733855
min,0.000000,2.040000,4.300000,1.000000,2.060606
25%,8.300000,2.950000,52.270000,69.000000,3.394124
50%,12.635000,3.280000,78.850000,114.000000,3.797468
75%,17.500000,4.520000,118.710000,181.000000,5.468320
max,38.300000,21.650000,798.222443,3811.000000,29.052632

           Marketing_Spend  Boxes_Shipped
Country
Australia        95.326670     126.773185
Brazil           95.716461     192.721463
Germany          95.221447     124.793226
India            95.551363     102.411697
Japan            95.472966     135.215146

,Order_ID,Product,Channel,Salesperson,Order_Date,Discount_Pct,Price_per_Box,Marketing_Spend,Boxes_Shipped,Amount,Price_Pre_Discount
Country,,,,,,,,,,,
Australia,91687,91687,91687,91687,91687,91474,91467,91481,91687,91687,91271
Brazil,52424,52424,52424,52424,52424,52296,52314,52311,52424,52424,52200
Germany,25037,25037,25037,25037,25037,24973,24970,24983,25037,25037,24917
India,17355,17355,17355,17355,17355,17314,17324,17308,17355,17355,17285
Japan,11541,11541,11541,11541,11541,11503,11515,11506,11541,11541,11480

In [ ]:
"""Parte 4.

    Utiliza Matplotlib o Seaborn para crear al menos dos gráficos:

    Gráfica de barras
    Histograma o dispersión

Ejemplo:
"""
import matplotlib.pyplot as plt

df['columna'].value_counts().plot(kind='bar')
plt.show()